# Generated by Django 4.2 on 2026-05-11 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_id', models.CharField(max_length=100)),
                ('paragraph_text', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(default='匿名用户', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.note')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
