# Generated by Django 5.0.4 on 2026-05-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skip_logic',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
