# Generated by Django 5.0.4 on 2026-05-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_skip_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='crm_webhook_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='crm_webhook_status',
            field=models.CharField(choices=[('pending', '待处理'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20),
        ),
    ]
